accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .views import signup, email_change, show_email_change_form, username_change, show_username_change_form, password_reset_form, password_reset_form2, password_reset_done, toggle_dark_mode, get_dark_mode


urlpatterns = [
    path("signup/", signup, name="signup"),

    #path("increase_score/", increase_score, name="increase_score"),

    path("username_change/", username_change, name="username_change"),

    path("email_change/", email_change, name="email_change"),

    path('password_reset1/', password_reset_form, name='password_reset1'),

    path('password_reset2/', password_reset_form2, name='password_reset2'),

    path('password_reset3/', password_reset_done, name='password_reset3'),
 
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users_hub/password_reset_confirm.html'), name='password_reset_confirm'),

    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users_hub/password_reset_complete.html'), name='password_reset_complete'),

    path("toggle-dark-mode/", toggle_dark_mode, name="toggle-dark-mode"),
    path("get-dark-mode/", get_dark_mode, name='get-dark-mode')
]

backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from sandbox.views import (
    main_sanbox_view,
    course_one_view,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),

    path('accounts/', include('django.contrib.auth.urls')),
    
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
    path('settings/', TemplateView.as_view(template_name='settings.html'), name='settings'),

    #path("python_course/", TemplateView.as_view(template_name="courses/python.html"), name="python_course"),
    #path("course1/", TemplateView.as_view(template_name="courses/course1.html"), name="course1"),
    #path("courses/<str:course_identifier>/", views.load_course, name="course_base"),

    path("community/", include("community.urls", namespace="community")),
    path("sandbox/", include("sandbox.urls", namespace="sandbox")),

]

community/urls.py
from django.urls import path
from . import views
from django.urls.converters import UUIDConverter
from django.views.generic.base import TemplateView

app_name = "community"

class UuidConverter(UUIDConverter):
    regex = '[0-9a-f-]+'

urlpatterns = [
    path("", views.list_of_posts, name="list_of_posts"),

    #path("create-post/", TemplateView.as_view(template_name="community/post_form.html"), name="create_post"),
    #path("create/", TemplateView.as_view(template_name="community/create_post.html"), name="create_post"),
    path("create/", views.get_post_form, name="create_url"),
    path("create_post/", views.create_post, name="create_post"), #

    path("<uuid:id>/", views.post_details, name="post_details"), # views function, name of path
    #path("<int:id>/", views.post_details, name="post_details"), # views function, name of path

    path("<uuid:post_id>/comment/", views.comment_for_post, name="comment_for_post"),

    path("upvote/<str:type>/<id>/", views.upvote, name="upvote"),

    path("demo_share/<uuid:id>", views.shared_link, name='demo_share'),
    path("check_notebook_link/", views.check_notebook_link, name="check_notebook_link"),
]

"""

comment_for_post is a model
but its comment_form is also embedded

create_post is a model
but why are we urling it?

^this solved the problem

"""

community/models.py
from typing import Any
from django.db import models
from django.utils import timezone
#from django.contrib.auth.models import User
from django.conf import settings
from django.db.models import F, Func, F, ExpressionWrapper, Value
from django.db.models import Case, When#Value, Greatest
from django.db.models import DateTimeField, IntegerField, DurationField, FloatField
from accounts.models import CustomUser

from django.utils import timezone

from datetime import datetime
#from datetime import timezone as dttz
import uuid
import json
import math

from django.conf import settings
User = settings.AUTH_USER_MODEL

# Create your models here.
class PostManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)

class Post(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    class Status(models.TextChoices):
        PRIVATE = "PV", "Draft"
        PUBLISHED = "PB", "Published"
    
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="posts"
    )
    title = models.CharField(max_length=250)
    #slug = models.SlugField(max_length=250)
    body = models.TextField()

    shared_link = models.ForeignKey(
        "community.SharedLink",
        on_delete=models.CASCADE,
        related_name="post_shared_link",
        null=True,
    )

    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    upvotes = models.IntegerField(default=0)
    upvoted_user_ids = models.TextField(default="[]")

    @property
    def upvoted_by_user(self):
        user_id = getattr(self, 'request', None).user.id
        #print(self.upvoted_user_ids)
        upvoted_user_ids = json.loads(self.upvoted_user_ids)
        #print("-")
        #print(user_id in upvoted_user_ids)
        #print("\\\\")
        return user_id in upvoted_user_ids
    
    status = models.CharField(
        max_length=2,
        choices=Status.choices,
        default=Status.PRIVATE
    )

    objects = models.Manager()
    publishedPosts = PostManager()

    class Meta:        
        ordering = [
            - (
                F('upvotes') + 1
            ) / (
                (
                    ExpressionWrapper(
                        datetime.now(timezone.utc) - F('publish'),
                        output_field=IntegerField()
                    ) / 86400000000 + 1
                ) ** 3
            ),
            #"-x_ord",
            "-publish"
        ]
        """indexes = [
            models.Index(fields=["-publish", "upvotes"]),
        ]"""

    def __str__(self):
        return f"Post {self.title} by  {self.author}"

class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name="comments"
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="comments"
    )
    #name = models.CharField(max_length=100)
    #email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    #active = models.BooleanField(default=True)
    upvotes = models.IntegerField(default=0)
    upvoted_user_ids = models.TextField(default="[]")

    @property
    def upvoted_by_user(self):
        user_id = getattr(self, 'request', None).user.id
        #print(self.upvoted_user_ids)
        upvoted_user_ids = json.loads(self.upvoted_user_ids)
        #print("-")
        #print(user_id in upvoted_user_ids)
        #print("\\\\")
        return user_id in upvoted_user_ids

    class Meta:
        ordering = ["-upvotes", "created"]
        indexes = [
            models.Index(fields=["-upvotes", "created"]),
        ]
    
    def __str__(self):
        return f"Comment by {self.name} on {self.post}: {self.body} with {self.upvotes} upvotes"

class SharedLink(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="shared_link_author",
        null=True
    )
    
    course_number = models.IntegerField(default=0)

    code = models.TextField(default="{}")

    objects = models.Manager()

community/forms.py
from collections.abc import Mapping
from typing import Any
from django.core.files.base import File
from django.db.models.base import Model
from django.forms.utils import ErrorList
from .models import Post, Comment, SharedLink
from django import forms
from django.core.validators import URLValidator
from django.core.exceptions import ValidationError
"""
def validate_notebook_link(notebook_link):
    print("in validate_notebook_link")

    if "/demo_share/" not in notebook_link:
        raise ValidationError("Invalid notebook link format.")
    
    parts = notebook_link.split("/demo_share/")

    try:
        shared_link = SharedLink.objects.get(id=parts[1].split("/")[0])
    except SharedLink.DoesNoteExist:
        raise ValidationError("No corresponding notebook ID found for the given link.")
"""
class PostForm(forms.ModelForm):
    notebook_link = forms.URLField(
        required=False,
        label="Notebook Link (optional)",
        #validators=[validate_notebook_link]
    )

    class Meta:
        model = Post
        fields = ["title", "body", "notebook_link"]
        widgets = {
            "title": forms.TextInput(
                attrs={
                    "placeholder": "Title",
                    "class": "form-control",
                }
            ),
            "body": forms.Textarea(
                attrs={
                    "placeholder": "Body (supports Markdown)",
                    "class": "form-control resizable",
                }
            ),
            
        }
    """
    def clean(self):
        cleaned_data = super().clean()

        validate_notebook_link(cleaned_data.get("notebook_link"))

        return cleaned_data
    """

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["body"]
        widgets = {
            "body": forms.Textarea(
                attrs={
                    "placeholder": "Body (supports Markdown)",
                    "class": "form-control resizable",
                    "rows": 5,
                }
            )
        }

community/views.py
import json

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.http import HttpResponse, HttpResponseRedirect, Http404, JsonResponse
from django.urls import reverse
from django.shortcuts import render, get_object_or_404

from django.views.decorators.http import require_POST

from .models import Post, Comment, PostManager, SharedLink
from .forms import PostForm, CommentForm

from django.core.exceptions import ValidationError

from sandbox.views import course_names

"""
import pytz
from django.utils import timezone

def convert_to_localtime(utctime):
    fmt = "%m/%d/%Y %H:%M"
    utc = utctime.replace(tzinfo=pytz.UTC)
    localtz = utc.astimezone(timezone.get_current_timezone())
    print(localtz)
    return localtz.strftime(fmt)
"""
def paginate_data(request, data, template_name, per_page=10, extra_context=None):
    paginator = Paginator(data, per_page)
    page_number = request.GET.get("page")

    try:
        paginated_data = paginator.page(page_number)
    except PageNotAnInteger:
        paginated_data = paginator.page(1)
    except EmptyPage:
        paginated_data = paginator.page(paginator.num_pages)
    
    context = {"data": paginated_data}
    if extra_context is not None:
        context.update(extra_context)

    return render(request, template_name, context)

def list_of_posts(request):
    posts = Post.publishedPosts.all()
    """post_paginator = Paginator(posts, 10)

    posts_page_number = request.GET.get("page")
    posts = post_paginator.get_page(posts_page_number)

    return render(
        request,
        "community/posts.html",
        {"posts": posts},
    )"""
    return paginate_data(request, posts, "community/posts.html")

def get_post_form(request): # gives the form to post
    return render(
        request,
        "community/create_post.html",
        {
            "form": PostForm()
        }
    )

@require_POST
def create_post(request): # add post based on form, need to fix TODO
    #print("request: ", request)
    if not request.user.is_authenticated:
        reponse_data = {
            "success": True,
            "message": "Log in to post",
        }

        return JsonResponse(reponse_data)

    post = None

    print("request.POST:", request.POST)
    
    form = PostForm(data = request.POST)

    #print("here half")

    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user

        notebook_link = form.cleaned_data.get("notebook_link")

        if "/demo_share/" in notebook_link:
            parts = notebook_link.split("/demo_share/")

            try:
                shared_link = SharedLink.objects.get(id=parts[1].split("/")[0])
                post.shared_link = shared_link
                print("GOOD xy")
            except Exception as e:
                print("BAD xy", e)
                pass
        
        post.status = "PB"
        post.save()

        # TODO why does post have author_id but comment has author object
        # get the arg for post id to send them to the new post

        #post_details_url = reverse("community:post_details", args=[post_id])
        post_details_url = reverse("community:post_details", args=[post.id])

        print("success")

        return HttpResponseRedirect(post_details_url)
    else:
        form = PostForm(instance=post)
    
    response_data = {
        "success": False,
        "errors": form.errors,
    }
    print("fail")

    return JsonResponse(response_data, status=400)

def post_details(request, id): # give details of a post, including the form
    try:
        post = get_object_or_404(
            Post,
            id=id,
            status=Post.Status.PUBLISHED
        )
        post.request = request

        comments = post.comments.all()#filter(active=True)
        for comment in comments:
            comment.request = request
        """comments_paginator = Paginator(comments, 10)

        comments_page_number = request.GET.get("page")
        comments = comments_paginator.get_page(comments_page_number)
        """
        form = CommentForm()
    except Post.DoesNotExist:
        raise Http404("No post found")
    #print(post.publish)
    #print(convert_to_localtime(post.publish))
    """return render(request, "community/detail.html", {
        "post": post,
        "comments": comments,
        "form": form,

        #"convert_to_localtime": convert_to_localtime,
    })"""
    return paginate_data(
        request,
        comments,
        "community/detail.html",
        extra_context={"post": post, "form": form}
    )

@require_POST
def comment_for_post(request, post_id): # add comment based on form filled
    if not request.user.is_authenticated:
        reponse_data = {
            "success": False,
            "message": "Log in to comment",
        }

        return JsonResponse(reponse_data)

    post = get_object_or_404(Post, id = post_id, status=Post.Status.PUBLISHED)
    comment = None

    form = CommentForm(data = request.POST)

    if form.is_valid():
        comment = form.save(commit = False)
        comment.post = post
        comment.author = request.user
        comment.save()

        post_details_url = reverse("community:post_details", args=[post_id])

        return HttpResponseRedirect(post_details_url)
    
    response_data = {
        "success": False,
        "errors": form.errors,
    }

    return JsonResponse(response_data, status=400)

def upvote(request, type, id):
    print("UPVOTE")
    if request.method == "POST":# and request.is_ajax():
        model_type = {
            "comment": Comment,
            "post": Post,
        }[type]

        obj = get_object_or_404(model_type, id=id)
        user_id = request.user.id

        upvoted_user_ids = json.loads(obj.upvoted_user_ids) if obj.upvoted_user_ids else []
        upvoted = user_id in upvoted_user_ids

        if not upvoted:
            upvoted_user_ids.append(user_id)
            obj.upvotes += 1
        else:
            upvoted_user_ids.remove(user_id)
            obj.upvotes -= 1

        obj.upvoted_user_ids = json.dumps(upvoted_user_ids)
        obj.save()

        return JsonResponse({"upvotes": obj.upvotes, "upvoted": not upvoted})

    return JsonResponse({"error": "Invalid request"})

"""

def upvote_comment(request, type, comment_id):
    if request.method == "POST":# and request.is_ajax():
        model_type = {
            "comment": Comment,
            "post": Post,
        }[type]

        obj = get_object_or_404(model_type, id=comment_id)
        user_id = request.user.id

        upvoted_user_ids = json.loads(obj.upvoted_user_ids) if upvoted_user_ids else []
        upvoted = user_id in upvoted_user_ids

        if not upvoted:
            upvoted_user_ids.append(user_id)
            obj.upvotes += 1
        else:
            upvoted_user_ids.remove(user_id)
            obj.upvotes -= 1

        obj.upvoted_user_ids = json.dumps(upvoted_user_ids)
        obj.save()

        return JsonResponse({"upvotes": obj.upvotes, "upvoted": not upvoted})

    return JsonResponse({"error": "Invalid request"})


"""

def shared_link(request, id):
    obj = get_object_or_404(SharedLink, id=id)

    return render(request, "shared_link.html", {
        "shared_link": obj,
        "name": course_names[obj.course_number]
    })

def check_notebook_link(request):
    if request.method == "POST":
        notebook_id = request.POST.get("notebook_id")

        try:
            shared_link = get_object_or_404(SharedLink, id=notebook_id)
            return JsonResponse({"isValid": True})
        except Exception:
            pass
    
    return JsonResponse({"isValid": False})

templates/community/comment_form.html
<h4>Add a new comment</h5>

{% if user.is_authenticated %}
  <form action="{% url 'community:comment_for_post' post.id %}" method="post">
    <div class="mb-4">
      {{ form.body }}
    </div>
    {% csrf_token %}
    <div class="to-right">
      <p><input type="submit" class="btn btn-primary no-dark-mode-styling"value="Add comment"></p>
    </div>
  </form>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
{% endif %}

templates/community/create_post.html
{% extends "base.html" %}

{% block title %}Create Post - Data With Mo{% endblock %}

{% block content %}

<div class="container-sm-2">

    <div class="text-center">
        <div class="badge bg-gradient-primary-to-secondary text-white mb-4"><div class="text-uppercase">Data with Mo</div></div>
    </div>
    <h2 class="display-3 fw-bolder mb-3"><span class="text-gradient d-inline">Create Post</span></h2>
    {% include "community/post_form.html" %}

    <!--<a href="/community/">
        Go back to the Posts
    </a>-->

</div>

{% endblock %}

templates/community/darkmode_functionality.html
{% csrf_token %}
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
    $(document).ready(function() {
        const darkModeToggle = $('#dark-mode-toggle');
        const body = $('body');

        // Function to toggle dark mode class and save user preference to the server
        darkModeToggle.on('click', function() {
            body.toggleClass('dark-mode');

            $.ajax({
                type: 'POST',
                url: '/accounts/toggle-dark-mode/',
                data: {
                    csrfmiddlewaretoken: "{{ csrf_token }}"
                },
                dataType: 'json',
                success: function(response) {
                    if (response.dark_mode) {
                        body.addClass('dark-mode');
                    } else {
                        body.removeClass('dark-mode');
                    }
                },
                error: function(error) {
                    console.log('Error:', error);
                }
            });
        });

        // Check user's preference from the server and set dark mode accordingly
        $.ajax({
            type: 'GET',
            url: '/accounts/get-dark-mode/',
            dataType: 'json',
            success: function(response) {
                darkModeToggle.prop("checked", response.dark_mode);
                if (response.dark_mode) {
                    body.addClass('dark-mode');
                }
            },
            error: function(error) {
                console.log('Error:', error);
            }
        });
    });
</script>

templates/community/detail.html
{% extends "base.html" %}

<!--{% load tz %}-->
{% load static %}

{% block title %}{{ post.title }} - Data With Mo{% endblock %}

{% block content %}

<div class="container-sm-2">

    <div class="text-center">
        <div class="badge bg-gradient-primary-to-secondary text-white mb-4"><div class="text-uppercase">Community</div></div>
    </div>
    <h2 class="display-6 fw-bolder mb-3"><span class="text-gradient d-inline">{{ post.title }}</span></h2>
    <div class="space-between mb-3">
        <div class="left-element">
            
            <!--<button
                class="upvote-button{% if post.upvoted_by_user %}button-not-upvoted{% else %}button-upvoted{% endif %}"
                data-type="post" data-post-id="{{ post.id }}"
            >{{ post.upvotes }} 🔼</button>-->
            <!--<div class="upvote-container">
                <div class="upvote-count">{{ post.upvotes }}</div>
                <div class="upvote-button-container">
                    <img
                        class="upvote-button{% if post.upvoted_by_user %} button-upvoted{% endif %}"
                        src="{% if post.upvoted_by_user %}button-upvoted.png{% else %}button-not-upvoted.png{% endif %}"
                        alt="Upvote"
                        data-type="post" data-post-id="{{ post.id }}"
                    />
                </div>
            </div>-->

            <!--<div class="upvote-container">
                <span class="upvote-count">{{ post.upvotes }}</span>
                <button
                    class="upvote-button{% if post.upvoted_by_user %} button-not-upvoted{% else %} button-upvoted{% endif %}"
                    data-type="post" data-post-id="{{ post.id }}"
                >
                    <img src="{% static 'assets/button-not-upvoted.png' %}" alt="Thumbs Up" class="upvote-icon">
                </button>
            </div>-->
            <div class="upvote-container">
                <span class="upvote-count">{{ post.upvotes }}</span>
                <button class="upvote-button {% if post.upvoted_by_user %}button-upvoted{% else %}button-not-upvoted{% endif %}" data-type="post" data-post-id="{{ post.id }}">
                    <div class="upvote-icon-container">
                        <img src="{% if post.upvoted_by_user %}{% static 'images/community/button-upvoted.png' %}{% else %}{% static 'images/community/button-not-upvoted.png' %}{% endif %}" alt="Thumbs Up" class="upvote-icon">
                        <div class="hover-circle"></div>
                    </div>
                </button>
            </div>

        </div>
        <div class="right-element">
            <b>
                {{ post.author.username}} &bull; {{ post.publish }}
            </b>
        </div>
    </div>
    
            {{ post.body|markdown|safe }}

            {% if post.shared_link %}
                <div class="mx-auto text-center">
                    <h6 class="fw-bolder"><a class="blue-link d-inline" href="http://127.0.0.1:8000/community/demo_share/{{ post.shared_link.id }}"
                        target="_blank">Attached Notebook Link:</a></h6>

                    <iframe src="http://127.0.0.1:8000/community/demo_share/{{ post.shared_link.id }}" title="sandbox"></iframe>
                </div>
            {% endif %}

            {% with data.paginator.count as total_comments %}
                <h4>
                    {{ total_comments }} comment{{ total_comments|pluralize }}
                </h4>
            {% endwith %}

            {% for comment in data %}<!--comments %}-->
                                
                {{ comment.body|markdown|safe }}

                <div class="space-between">
                    <div class="left-element">
                        <!--<button
                            class="upvote-button{% if post.upvoted_by_user %}button-not-upvoted{% else %}button-upvoted{% endif %}"
                            data-type="comment" data-comment-id="{{ comment.id }}"
                        >{{ comment.upvotes }} 🔼</button>-->
                        <div class="upvote-container">
                            <span class="upvote-count">{{ comment.upvotes }}</span>
                            <button class="upvote-button {% if comment.upvoted_by_user %}button-upvoted{% else %}button-not-upvoted{% endif %}" data-type="comment" data-comment-id="{{ comment.id }}">
                                <div class="upvote-icon-container">
                                    <img src="{% if comment.upvoted_by_user %}{% static 'images/community/button-upvoted.png' %}{% else %}{% static 'images/community/button-not-upvoted.png' %}{% endif %}" alt="Thumbs Up" class="upvote-icon">
                                    <div class="hover-circle"></div>
                                </div>
                            </button>
                        </div>
                    </div>
                    <div class="right-element">
                        <p>
                            <!--Comment {{ forloop.counter }} by -->
                            {{ comment.author.username }} &bull; {{ comment.created }}
                        </p>
                    </div>
                </div>

                <hr>
            
        {% empty %}
            <p>There are no comments.</p>
        {% endfor %}

        {% if data.paginator.count > 0 %}
            {% include 'community/pagination.html' %}
        {% endif %}

        {% if user.is_authenticated %}

            {% include "community/comment_form.html" %}
            {% include 'community/upvote_functionality.html' %}

        {% endif %}

    <!--<a href="/community/">
        Go back to the Posts
    </a>-->

</div>

<style>
    iframe {
      width: 100%;
      max-width: 800px;
      border: none;

      height: 500px;
      
      display: flex;
      align-items: center;
      justify-content: center;
      margin: 0;
    }
</style>

{% endblock %}

templates/community/post_form.html
{% if user.is_authenticated %}

<form id="postForm" action="{% url 'community:create_post' %}" method="post">
    <!-- create_post to create_url -->
    <div class="mb-4">
        {{ form.title }}
    </div>
    <div class="mb-4">
        {{ form.body }}
    </div>
    <div class="mb-4">
        <input type="url" name="notebook_link" placeholder="Notebook Link (optional)" class="form-control" id="id_notebook_link">
    </div>
    {% csrf_token %}
    <div class="to-right">
        <p><input type="submit" class="btn btn-primary no-dark-mode-styling" value="Post"></p>
    </div>
</form>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

<script>
    $(document).ready(function () {
        $("#postForm").submit(function (event) {
            event.preventDefault();

            var notebookLink = $("#id_notebook_link").val();

            isValidNotebookLink(notebookLink, function (isValid) {
                if (!isValid) {
                    alert("Invalid notebook link. Please enter a valid notebook link.");
                } else {
                    $("#postForm")[0].submit();
                }
            });
        });

        function isValidNotebookLink(notebookLink, callback) {
            if (notebookLink == "") {
                callback(true);
            } else if (!notebookLink.includes("/demo_share/")) {
                callback(false);
            } else {
                var parts = notebookLink.split("/demo_share/");
                var notebookId = parts[1].split("/")[0];

                $.ajax({
                    url: "/community/check_notebook_link/",
                    method: "POST",
                    data: {
                        notebook_id: notebookId,
                        csrfmiddlewaretoken: "{{ csrf_token }}",
                    },
                    success: function (data) {
                        callback(data.isValid);
                    },
                    error: function () {
                        callback(false);
                    },
                });
            }
        }
    });
</script>

 

{% else %}
    <p>You are not logged in</p>
    <a href="{% url 'login' %}">Log In</a>
{% endif %}

templates/community/posts.html
{% extends "base.html" %}

{% block title %}Community Posts - Data With Mo{% endblock %}

{% load static %}

{% block content %}

<div class="container-sm-2">

    <div class="text-center">
        <div class="badge bg-gradient-primary-to-secondary text-white"><div class="text-uppercase">Data with Mo</div></div>
        <h2 class="display-3 fw-bolder mb-3"><span class="text-gradient d-inline">Community Posts</span></h2>
    </div>

    <div class="text-center">
        <div class="justify-content-center mb-2">
            <a
                class="btn btn-primary no-dark-mode-styling"
                href="{% url 'community:create_url' %}"
            >Create Post</a>
        </div>

        {% for post in data %}<!--posts %}-->

            <a href="{% url 'community:post_details' post.id %}">
                <div class="courseitem">
                    <!--<strong class="text-gradient d-inline">{{ post.title }}</strong>
                    <div class="space-between">
                        <p>
                            {{ post.upvotes }} 🔼
                        </p>
                        <p>
                            {{ post.days_since }} {{ post.author.username }} &bull; {{ post.publish }}
                        </p>
                    </div>-->
                    
                    <div class="post-preview">
                        <div class="upvote-preview">
                            <!--<pv2>
                                {{ post.upvotes }} 🔼
                            </pv2>-->
                            <div class="upvote-container">
                                <span class="upvote-count">{{ post.upvotes }}</span>
                                    <div class="upvote-icon-container">
                                        <img src="{% static 'images/community/button-upvoted.png' %}" alt="Thumbs Up" class="upvote-icon">
                                    </div>
                            </div>
                        </div>
                        
                        <div class="post-preview-details">
                            <div class="post-preview-title text-gradient d-inline">
                                <pv2>
                                    {{ post.title }}
                                </pv2>
                            </div>
                            <div class="post-preview-subtitle">
                                <pv2>
                                    {{ post.days_since }} {{ post.author.username }} &bull; {{ post.publish }}
                                </pv2>
                            </div>
                        </div>
                    </div>
                
                </div>
            </a>

        {% endfor %}

        {% if data.paginator.count > 0 %}
            {% include 'community/pagination.html' %}
        {% endif %}

    </div>

</div>

{% endblock %}