accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .views import signup, email_change, show_email_change_form, username_change, show_username_change_form, password_reset_form, password_reset_form2, password_reset_done, toggle_dark_mode, get_dark_mode


urlpatterns = [
    path("signup/", signup, name="signup"),

    #path("increase_score/", increase_score, name="increase_score"),

    path("username_change/", username_change, name="username_change"),

    path("email_change/", email_change, name="email_change"),

    path('password_reset1/', password_reset_form, name='password_reset1'),

    path('password_reset2/', password_reset_form2, name='password_reset2'),

    path('password_reset3/', password_reset_done, name='password_reset3'),
 
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users_hub/password_reset_confirm.html'), name='password_reset_confirm'),

    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users_hub/password_reset_complete.html'), name='password_reset_complete'),

    path("toggle-dark-mode/", toggle_dark_mode, name="toggle-dark-mode"),
    path("get-dark-mode/", get_dark_mode, name='get-dark-mode')
]

backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from sandbox.views import (
    main_sanbox_view,
    course_one_view,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),

    path('accounts/', include('django.contrib.auth.urls')),
    
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
    path('settings/', TemplateView.as_view(template_name='settings.html'), name='settings'),

    #path("python_course/", TemplateView.as_view(template_name="courses/python.html"), name="python_course"),
    #path("course1/", TemplateView.as_view(template_name="courses/course1.html"), name="course1"),
    #path("courses/<str:course_identifier>/", views.load_course, name="course_base"),

    path("community/", include("community.urls", namespace="community")),
    path("sandbox/", include("sandbox.urls", namespace="sandbox")),

]

community/urls.py
from django.urls import path
from . import views
from django.urls.converters import UUIDConverter
from django.views.generic.base import TemplateView

app_name = "community"

class UuidConverter(UUIDConverter):
    regex = '[0-9a-f-]+'

urlpatterns = [
    path("", views.list_of_posts, name="list_of_posts"),

    #path("create-post/", TemplateView.as_view(template_name="community/post_form.html"), name="create_post"),
    #path("create/", TemplateView.as_view(template_name="community/create_post.html"), name="create_post"),
    path("create/", views.get_post_form, name="create_url"),
    path("create_post/", views.create_post, name="create_post"), #

    path("<uuid:id>/", views.post_details, name="post_details"), # views function, name of path
    #path("<int:id>/", views.post_details, name="post_details"), # views function, name of path

    path("<uuid:post_id>/comment/", views.comment_for_post, name="comment_for_post"),

    path("upvote/<str:type>/<id>/", views.upvote, name="upvote"),

    path("demo_share/<uuid:id>", views.shared_link, name='demo_share'),
    path("check_notebook_link/", views.check_notebook_link, name="check_notebook_link"),
]

"""

comment_for_post is a model
but its comment_form is also embedded

create_post is a model
but why are we urling it?

^this solved the problem

"""

templates/about.html
{% extends 'base.html' %}

{% block title %}About Us - Data With Mo{% endblock %}

{% block content %}
<h1> Data knowledge and skills that you can actually apply in the real world - no jargon, no fluff, just the useful stuff </h1>
{% endblock %}

{% block footer %}{% endblock %}

templates/base.html
{% load static %}


<!DOCTYPE html>
<html height="100%">
<head>
  <meta charset="utf-8">
  <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}">
  <title>{% block title %}Data With Mo{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/gem.css' %}">
  <link rel="stylesheet" href="{% static 'css/pygments_style.css' %}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter" rel="stylesheet">
</head>
<body>

  {% if user.is_authenticated %}
  <nav>
    <!--<div class="row gx-5 align-items-center">-->
      <a href="{% url 'home' %}">Home</a>
      <a href="{% url 'community:list_of_posts' %}">Community</a>
      <a href="{% url 'settings' %}" id="profilelink">
          {{ user.username }}
      </a>
    <!--</div>-->
  </nav>
  {% endif %}
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

<!--{% csrf_token %}
<script src="{% static 'js/darkmode.js' %}"></script>-->
{% include 'community/darkmode_functionality.html' %}

templates/home.html
{% extends 'base.html' %}

{% block title %}Home - Data With Mo{% endblock %}

{% block content %}
{% if user.is_authenticated %}

<!-- -->
  <section id="scroll">
    <div class="container px-5">

<div class="container-sm-2">

  <div class="text-center">
    <div class="badge bg-gradient-primary-to-secondary text-white"><div class="text-uppercase">Data with Mo</div></div>
    <h2 class="display-3 fw-bolder mb-3"><span class="text-gradient d-inline">{{ user.username }}'s Courses</span></h2>
  </div>

  <!--<section id="scroll">
    <div class="container px-5">-->
      <div class="text-center">
        <!--<h2 class="display-3 fw-bolder mb-3">
          <span class="text-gradient d-inline">Your Courses</span>
        </h2>-->
        
        <!-- btn btn-primary btn-lg px-5 py-3 me-sm-3 fs-6 fw-bolder -->

        <a href="{% url 'sandbox:main_sandbox' %}">
          <div class="courseitem">
            <strong class="text-gradient d-inline">Sandbox</strong>
            <div class="mb-2"></div>
            <p>A basic sandbox to do whatever you would like to.</p>
          </div>
        </a>

        <a href="{% url 'sandbox:python_course' %}">
          <div class="courseitem">
            <strong class="text-gradient d-inline">Python Starter Course</strong>
            <div class="mb-2"></div>
            <p>Learn introductory Python concepts with fun themes to prepare yourself for using Python with Data.</p>
          </div>
        </a>

        <div class="mb-2"></div>
        <a href="{% url 'sandbox:course_two' %}">
          <div class="courseitem">
            <strong class="text-gradient d-inline">Course 1: LinkedIn Jobs</strong>
            <div class="mb-2"></div>
            <p>Learn a Linear Regression model with a LinkedIn Data Analytics Jobs dataset.</p>
          </div>
        </a>
        <div class="mb-2"></div>
        <a href="{% url 'sandbox:course_three' %}">
          <div class="courseitem">
            <strong class="text-gradient d-inline">Course 2: Credit Card Churn</strong>
            <div class="mb-2"></div>
            <p>Learn a Support Vector Machine with a Credit Card Churn dataset.</p>
          </div>
        </a>
        <div class="mb-2"></div>
        <a href="{% url 'sandbox:course_four' %}">
          <div class="courseitem">
            <strong class="text-gradient d-inline">Course 3: Stocks</strong>
            <div class="mb-2"></div>
            <p>Learn a Logistic Regression model with a Stock Data dataset.</p>
          </div>
        </a>
        <div class="mb-2"></div>

        </div>
      </div>
    <!--</div>
  </section>-->

</div>

{% else %}
  <div id="landing">
    <div class="column" style="clear: both;">
      <h1 id="web_title">Real World Data Analytics</h1>
      <p id="web_description"> Data knowledge and skills that you can actually apply in the real world - no jargon, no fluff, just the useful stuff </p>
      <a href="{% url 'login' %}" class="register">Log In</a> <a href="{% url 'signup' %}" class="register">Sign Up</a>
    </div>
    {% load static %}
    <div class="column">
      <img id="landing_img" src="{% static 'Vector.png' %}">
    </div>
  </div>
{% endif %}
{% endblock %}

templates/sandbox.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ name }} - Data With Mo{% endblock %}
{% block content %}
{% if user.is_authenticated %}

<div class="text-center">
    <h2 class="display-3 fw-bolder mb-3"><span class="text-gradient d-inline">{{ name }}</span></h2>

    <!--<div class="bar">--
        <p class="text-gradient display-6">may take time to load</p>
    <--</div>-->

    <div class="widget-row-center">
        <button class="btn btn-primary no-dark-mode-styling" onclick="save()">Save Work</button>
        <a
            class="btn btn-primary no-dark-mode-styling"
            href="{{ share_url }}"
            target="_blank"
        >Share Link</a>
    </div>

    
    <div class="mb-3"></div>
</div>

<script>
    setTimeout(toggle, 3000);
    function toggle() {
        window.frames.jupyterlab.postMessage({ type: 'from-host-to-iframe', dark: '{{user.userdata.darkmode}}'});
    }
</script>

<div class="holder">
    <div>
        <div class="load-widget">
            {% comment %} This is strange only works when add domain ***Remember to check when have actually domain name*** {% endcomment %}
            {% if course == 0 %}
                <embed class='iFrameSandbox' name="jupyterlab" width='100%' height='700' title="sandbox"
                src="http://127.0.0.1:8000/public/jupyter/lab/index.html" ></embed>
            {% else %}
                <embed class='hide-sidebar iFrameSandbox' name="jupyterlab" width='100%' height='700' title="sandbox"
                src="http://127.0.0.1:8000/public/jupyter/lab/index.html?path=Course_{{course}}.ipynb"></embed>
            {% endif %}
        </div>
        <div class="loading-text text-gradient display-6">Loading...</div>
    </div>
<script>
    //Saves it when closing the tab as well as saving it when you press ctrl-s
    window.addEventListener('beforeunload', function(event) {
        save()
    });
    document.onkeyup = function(e) {
        if (e.ctrlKey && e.which == 83) {
            console.log("saving...")
            save()
        }
    };
    //Clears all the data from the db and then loads in the user data
    do_loading_functions()
    function do_loading_functions() {
        clear()
        restart_if_has_data()
        load_user_data()
        reload_three_times()
    }
    function reload_three_times() {
        if ( window.localStorage ) {
            if(!localStorage.getItem('firstLoad')) {
                console.log("")
                localStorage['firstLoad'] = false;
                window.location.reload();
            }
            else if (localStorage['firstLoad'] == false) {
                console.log("")
                localStorage['firstLoad'] = true;
                wait_one_second();
                window.location.reload();
            }
            else
                localStorage.removeItem('firstLoad');
        }
    }
    function load_user_data() {
        let data = null
        if ({{course}} == 0){
            data = "{{ user.userdata.saved_code }}"
        }
        else if ({{course}} == 1) {
            data = "{{ user.userdata.saved_code_course_one }}"
        }
        else if ({{course}} == 2) {
            data = "{{ user.userdata.saved_code_course_two }}"
        }
        else if ({{course}} == 3) {
            console.log("c")
            data = "{{ user.userdata.saved_code_course_three }}"
        }
        else if ({{course}} == 4) {
            console.log("c")
            data = "{{ user.userdata.saved_code_course_four }}"
        }
        data = htmlDecode(data)
        data = JSON.parse(data)
        const request = indexedDB.open('JupyterLite Storage');
        request.onsuccess = function (event) {
            const db = event.target.result;
            const transaction = db.transaction('files', "readwrite");
            const objectStore = transaction.objectStore('files');
            for (const key in data) {
                if (data.hasOwnProperty(key)) {
                    const request = objectStore.add(data[key], key);
                }
            }   
        };
    }       
    function htmlDecode(input) {
        input = input.substring(2);
        input = input.replace(/#x27;/g, "");
        input = input.slice(0, -1);
        var doc = new DOMParser().parseFromString(input, "text/html");
        return doc.documentElement.textContent;
    }
    function restart_if_has_data() {
        // Open a database connection
        var request = indexedDB.open('JupyterLite Storage', 1);
        // Handle the database open success event
        request.onsuccess = function(event) {
            var db = event.target.result;
  
            // Open a transaction on the object store
            var transaction = db.transaction('files', 'readonly');
            var objectStore = transaction.objectStore('files');
  
            // Create a request to count the records in the object store
            var countRequest = objectStore.count();
  
            // Handle the count success event
            countRequest.onsuccess = function(event) {
                var count = event.target.result;
                if (count === 0) {
                    // The object store is clear (empty)
                    console.log('Object store is empty.');
                } 
                else {
                    location.reload();
                }
            };
        };
    }
    function clear() {
        const request = indexedDB.open('JupyterLite Storage');
        request.onsuccess = function (event) {
            // Opens an object in DB
            const db = event.target.result;
            const transaction = db.transaction('files', 'readwrite');
            const objectStore = transaction.objectStore('files');
            objectStore.clear()
      };
  
    }
    function save() {
        //gets all the files in the database and then stores it in the user model as a string
        const request = indexedDB.open('JupyterLite Storage');
        // Create an object to store the key-value pairs
        const filesObject = {};
        // If accessing the Database was a success
        request.onsuccess = function (event) {
            // Opens an object in DB
            const db = event.target.result;
            const transaction = db.transaction('files', 'readonly');
            const objectStore = transaction.objectStore('files');
            // Creates a list of each key in the object
            const request = objectStore.openCursor();
            request.onsuccess = function (event) {
                const cursor = event.target.result;
                if (cursor) {
                    //Loops through each result
                    const value = cursor.value;
                    const key = cursor.key;
    
                    filesObject[key] = value;
    
                    cursor.continue();
                } 
                else {
                    //Calls when all the results are listed
                    if ({{course}} == 0){
                        //Calls when all the results are listed
                        console.log("Finished listing");
                        const jsonString = JSON.stringify(filesObject);
                        console.log(jsonString);
                        fetch('{% url "sandbox:save_data" %}', {
                             method: 'POST',
                            headers: {
                                'X-CSRFToken': '{{ csrf_token }}',  // Include CSRF token for security
                                'Content-Type': 'application/json', // Specify content type as JSON
                            },
                            body: jsonString
                        })
                    }
                    else if ({{course}} == 1) {
                        //Calls when all the results are listed
                        console.log("Finished listing");
                        const jsonString = JSON.stringify(filesObject);
                        console.log(jsonString);
                        fetch('{% url "sandbox:save_course_one_data" %}', {
                             method: 'POST',
                            headers: {
                                'X-CSRFToken': '{{ csrf_token }}',  // Include CSRF token for security
                                'Content-Type': 'application/json', // Specify content type as JSON
                            },
                            body: jsonString
                        })
                    }
                    else if ({{course}} == 2) {
                        //Calls when all the results are listed
                        console.log("Finished listing");
                        const jsonString = JSON.stringify(filesObject);
                        console.log(jsonString);
                        fetch('{% url "sandbox:save_course_two_data" %}', {
                             method: 'POST',
                            headers: {
                                'X-CSRFToken': '{{ csrf_token }}',  // Include CSRF token for security
                                'Content-Type': 'application/json', // Specify content type as JSON
                            },
                            body: jsonString
                        })
                    }
                    else if ({{course}} == 3) {
                        //Calls when all the results are listed
                        console.log("Finished listing");
                        const jsonString = JSON.stringify(filesObject);
                        console.log(jsonString);
                        fetch('{% url "sandbox:save_course_three_data" %}', {
                             method: 'POST',
                            headers: {
                                'X-CSRFToken': '{{ csrf_token }}',  // Include CSRF token for security
                                'Content-Type': 'application/json', // Specify content type as JSON
                            },
                            body: jsonString
                        })
                    }
                    else if ({{course}} == 4) {
                        //Calls when all the results are listed
                        console.log("Finished listing");
                        const jsonString = JSON.stringify(filesObject);
                        console.log(jsonString);
                        fetch('{% url "sandbox:save_course_four_data" %}', {
                             method: 'POST',
                            headers: {
                                'X-CSRFToken': '{{ csrf_token }}',  // Include CSRF token for security
                                'Content-Type': 'application/json', // Specify content type as JSON
                            },
                            body: jsonString
                        })
                    }
                }
            };
    
            // Handle any errors
            request.onerror = function (event) {
                console.error('Error:', event.target.error);
            };
        };
    
    }
</script>
    
</div>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
{% endif %}
{% endblock %}

templates/settings.html
{% extends 'base.html' %}

{% block title %}Settings{% endblock %}

{% block content %}
<div class="container px-5">
    <h2 class="display-3 fw-bolder mb-3">
        <span class="text-gradient d-inline">Settings</span>
    </h2>

    <div class="mb-2">
        <p><a href="{% url 'username_change' %}">Change Username</a></p>
        <p><a href="{% url 'email_change' %}">Change Email</a></p>
    </div>

    <div class="widget-row">
        <label class="switch mb-4">
            <input type="checkbox" id="dark-mode-toggle">
            <span class="slider round"></span>
        </label>
        <p>Dark Mode</p>
    </div>

    <p>
        <a
            class="btn btn-primary"
            href="{% url 'logout' %}"
        >Log Out</a>
    </p>
</div>
{% endblock %}

templates/shared_link.html
{% load static %}

<link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}">

{% include 'community/darkmode_functionality.html' %}

<link rel="stylesheet" href="{% static 'css/gem.css' %}">
<link rel="stylesheet" href="{% static 'css/pygments_style.css' %}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter" rel="stylesheet">

<title>{% block title %}{{ shared_link.author.username }}'s {{ name }}{% endblock %}</title>

{% block content %}

<div class="mb-3"></div>

<div class="text-center">
    <h6 class="fw-bolder mb-2"><span class="text-gradient d-inline">{{ shared_link.author.username }}'s {{ name }}</span></h6>

    <!--<p class="text-gradient">may take time to load</p>-->
</div>

<script>
    setTimeout(toggle, 3000);
    function toggle() {
        window.frames.jupyterlab.postMessage({ type: 'from-host-to-iframe', dark: '{{user.userdata.darkmode}}'});
    }
</script>

<div class="holder">
    
    <div>
        <div class="load-widget">
            {% comment %} This is strange only works when add domain ***Remember to check when have actually domain name*** {% endcomment %}
            {% if shared_link.course_number == 0 %}
                <embed class='iFrameSandbox' name="jupyterlab" width='100%' height='700' title="sandbox"
                src="http://127.0.0.1:8000/public/jupyter/lab/index.html"></embed>
            {% else %}
                <embed class='hide-sidebar iFrameSandbox' name="jupyterlab" width='100%' height='700' title="sandbox"
                src="http://127.0.0.1:8000/public/jupyter/lab/index.html?path=Course_{{ shared_link.course_number }}.ipynb"></embed>
            {% endif %}
        </div>
        <div class="loading-text text-gradient display-6">Loading...</div>
    </div>
    <script>
    /*/Saves it when closing the tab as well as saving it when you press ctrl-s
    window.addEventListener('beforeunload', function(event) {
        save()
    });
    document.onkeyup = function(e) {
        if (e.ctrlKey && e.which == 83) {
            console.log("saving...")
            save()
        }
    };*/
    //Clears all the data from the db and then loads in the user data
    do_loading_functions()
    function do_loading_functions() {
        clear()
        restart_if_has_data()
        load_user_data()
        reload_three_times()
    }
    function reload_three_times() {
        if ( window.localStorage ) {
            if(!localStorage.getItem('firstLoad')) {
                console.log("")
                localStorage['firstLoad'] = false;
                window.location.reload();
            }
            else if (localStorage['firstLoad'] == false) {
                console.log("")
                localStorage['firstLoad'] = true;
                wait_one_second();
                window.location.reload();
            }
            else
                localStorage.removeItem('firstLoad');
        }
    }
    function load_user_data() {
        let data = "{{ shared_link.code }}"
        
        data = htmlDecode(data)
        data = JSON.parse(data)
        const request = indexedDB.open('JupyterLite Storage');
        request.onsuccess = function (event) {
            const db = event.target.result;
            const transaction = db.transaction('files', "readwrite");
            const objectStore = transaction.objectStore('files');
            for (const key in data) {
                if (data.hasOwnProperty(key)) {
                    const request = objectStore.add(data[key], key);
                }
            }   
        };
    }       
    function htmlDecode(input) {
        input = input.substring(2);
        input = input.replace(/#x27;/g, "");
        input = input.slice(0, -1);
        var doc = new DOMParser().parseFromString(input, "text/html");
        return doc.documentElement.textContent;
    }
    function restart_if_has_data() {
        // Open a database connection
        var request = indexedDB.open('JupyterLite Storage', 1);
        // Handle the database open success event
        request.onsuccess = function(event) {
            var db = event.target.result;
  
            // Open a transaction on the object store
            var transaction = db.transaction('files', 'readonly');
            var objectStore = transaction.objectStore('files');
  
            // Create a request to count the records in the object store
            var countRequest = objectStore.count();
  
            // Handle the count success event
            countRequest.onsuccess = function(event) {
                var count = event.target.result;
                if (count === 0) {
                    // The object store is clear (empty)
                    console.log('Object store is empty.');
                } 
                else {
                    location.reload();
                }
            };
        };
    }
    function clear() {
        const request = indexedDB.open('JupyterLite Storage');
        request.onsuccess = function (event) {
            // Opens an object in DB
            const db = event.target.result;
            const transaction = db.transaction('files', 'readwrite');
            const objectStore = transaction.objectStore('files');
            objectStore.clear()
      };
  
    }
    /*
    function save() {
        //gets all the files in the database and then stores it in the user model as a string
        const request = indexedDB.open('JupyterLite Storage');
        // Create an object to store the key-value pairs
        const filesObject = {};
        // If accessing the Database was a success
        request.onsuccess = function (event) {
            // Opens an object in DB
            const db = event.target.result;
            const transaction = db.transaction('files', 'readonly');
            const objectStore = transaction.objectStore('files');
            // Creates a list of each key in the object
            const request = objectStore.openCursor();
            request.onsuccess = function (event) {
                const cursor = event.target.result;
                if (cursor) {
                    //Loops through each result
                    const value = cursor.value;
                    const key = cursor.key;
    
                    filesObject[key] = value;
    
                    cursor.continue();
                } 
                else {
                    //Calls when all the results are listed
                    if ({{course}} == 0){
                        //Calls when all the results are listed
                        console.log("Finished listing");
                        const jsonString = JSON.stringify(filesObject);
                        console.log(jsonString);
                        fetch('{% url "sandbox:save_data" %}', {
                             method: 'POST',
                            headers: {
                                'X-CSRFToken': '{{ csrf_token }}',  // Include CSRF token for security
                                'Content-Type': 'application/json', // Specify content type as JSON
                            },
                            body: jsonString
                        })
                    }
                    else if ({{course}} == 1) {
                        //Calls when all the results are listed
                        console.log("Finished listing");
                        const jsonString = JSON.stringify(filesObject);
                        console.log(jsonString);
                        fetch('{% url "sandbox:save_course_one_data" %}', {
                             method: 'POST',
                            headers: {
                                'X-CSRFToken': '{{ csrf_token }}',  // Include CSRF token for security
                                'Content-Type': 'application/json', // Specify content type as JSON
                            },
                            body: jsonString
                        })
                    }
                    else if ({{course}} == 2) {
                        //Calls when all the results are listed
                        console.log("Finished listing");
                        const jsonString = JSON.stringify(filesObject);
                        console.log(jsonString);
                        fetch('{% url "sandbox:save_course_two_data" %}', {
                             method: 'POST',
                            headers: {
                                'X-CSRFToken': '{{ csrf_token }}',  // Include CSRF token for security
                                'Content-Type': 'application/json', // Specify content type as JSON
                            },
                            body: jsonString
                        })
                    }
                    else if ({{course}} == 3) {
                        //Calls when all the results are listed
                        console.log("Finished listing");
                        const jsonString = JSON.stringify(filesObject);
                        console.log(jsonString);
                        fetch('{% url "sandbox:save_course_three_data" %}', {
                             method: 'POST',
                            headers: {
                                'X-CSRFToken': '{{ csrf_token }}',  // Include CSRF token for security
                                'Content-Type': 'application/json', // Specify content type as JSON
                            },
                            body: jsonString
                        })
                    }
                    else if ({{course}} == 4) {
                        //Calls when all the results are listed
                        console.log("Finished listing");
                        const jsonString = JSON.stringify(filesObject);
                        console.log(jsonString);
                        fetch('{% url "sandbox:save_course_four_data" %}', {
                             method: 'POST',
                            headers: {
                                'X-CSRFToken': '{{ csrf_token }}',  // Include CSRF token for security
                                'Content-Type': 'application/json', // Specify content type as JSON
                            },
                            body: jsonString
                        })
                    }
                }
            };
    
            // Handle any errors
            request.onerror = function (event) {
                console.error('Error:', event.target.error);
            };
        };
    
    }
    */
    </script>
    <!--<button onclick="save()">Save</button>-->
</div>

{% endblock %}